name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Baixa o codigo fonte
      - uses: actions/setup-node@v4
        with:
          node-version: '23.3.0'
      - uses: actions/checkout@v3
      - name: Instalar dependencias
        run: npm i

      - name: Buidlar aplicação
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run ls
        uses: actions/download-artifact@v3
        with:
          name: build-dist
          path: dist/
        run: ls -lah -tr

